# Generated by Django 4.2 on 2023-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HospitalAppointment", "0002_user_surname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={"verbose_name": "Doktor", "verbose_name_plural": "Doktorlar"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="surname",
        ),
        migrations.AddField(
            model_name="doctor",
            name="city",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="clinic",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="county",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="hospital",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tcno",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
