# Generated by Django 4.2 on 2023-04-28 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("HospitalAppointment", "0003_alter_doctor_options_remove_user_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="tcno",
            new_name="id_number",
        ),
    ]
