# Generated by Django 4.2 on 2023-04-29 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HospitalAppointment", "0004_rename_tcno_user_id_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="id_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "invalid": "Lütfen geçerli bir TC kimlik numarası giriniz.",
                    "unique": "Bu TC Kimliğe ait bir hesap zaten bulunmakta.",
                },
                help_text="TC Kimlik numaranızı giriniz.",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\s*?[0-9]{1,11}\\s*$",
                        "Lütfen geçerli bir TC kimlik numarası giriniz.",
                    )
                ],
            ),
        ),
    ]
