# Generated by Django 4.2 on 2023-05-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HospitalAppointment", "0006_doctor_dates_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="dates",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Şehir"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="clinic",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Klinik"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="county",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="İlçe"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="hospital",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Hastane"
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="İsim"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(blank=True, null=True, verbose_name="Doğum Tarihi"),
        ),
        migrations.CreateModel(
            name="AppointmentDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Tarih ve Saat")),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HospitalAppointment.doctor",
                        verbose_name="Doktor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Randevu Tarihi",
                "verbose_name_plural": "Randevu Tarihleri",
            },
        ),
    ]
