# Generated by Django 4.2.1 on 2023-05-18 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "HospitalAppointment",
            "0008_alter_appointment_doctor_alter_appointment_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "invalid": "Lütfen geçerli bir TC kimlik numarası giriniz.",
                    "unique": "Bu TC Kimliğe ait bir hesap zaten bulunmakta.",
                },
                help_text="TC Kimlik numaranızı giriniz.",
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\s*?[0-9]{1,11}\\s*$",
                        "Lütfen geçerli bir TC kimlik numarası giriniz.",
                    )
                ],
                verbose_name="TC Kimlik Numarası",
            ),
        ),
    ]
