# Generated by Django 4.2.1 on 2023-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HospitalAppointment", "0009_alter_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Başlık"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="İçerik"),
                ),
                ("date", models.DateTimeField(verbose_name="Tarih")),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Bloglar",
            },
        ),
    ]
